### ISSUE TITLE
Problem with SSL

### ISSUE THREAD

**Issue by Velociraptor85** [VeNoMouS/Sick-Beard#10]
Hej,
I have a problem with scrapping torrentz2 page ... or at least thats the only one I get these Errors:

> SEARCHQUEUE-RSS-SEARCH :: [Torrentz] getURL() Error loading Torrentz URL: [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

Also I found some info [here](https://stackoverflow.com/questions/30538542/tlsv1-alert-internal-error-during-handshake) and [here](https://unix.stackexchange.com/questions/169034/curl-35-error14077438ssl-routinesssl23-get-server-hellotlsv1-alert-intern#169428)

So I guess it has something to do with how it connects to the site
- `curl -vlkL https://torrentz2.eu/ --ciphers DHE-RSA-AES256-SHA` -> ERROR
- `curl -vlkL https://torrentz2.eu/` -> No Problem ... uses `ECDHE-ECDSA-AES128-GCM-SHA256` SSLv3

openssl versoin: `OpenSSL 1.0.1t  3 May 2016`

maybe you can give me a hint :)

**Comment by VeNoMouS** [comment]
Curl wont help you, curl uses its own librarys, we use python requests.

<typing on the fly..>

```
import requests
sess = requests.session()
ret = sess.get('https://torrentz2.eu/', verify=False, timeout=30)
print ret.content
```

Is this like an embedded system such as a synology etc?

Also what version is your python?

I would recommend (if you have pip) upgrading pyopenssl and pyasn1 , you will most likely find that will resolve your issue.

via 

```pip install --upgrade pyopenssl```
```pip install --upgrade pyasn1```

**Comment by Velociraptor85** [comment]
Python 2.7.3 on a Debian Wheezy 
pip install --upgrade pyopenssl give me errors 
aptitude python-openssl = 0.13-2+deb7u1

**Comment by VeNoMouS** [comment]
well... tbh with pip you get ```pyOpenSSL-16.2.0```

https://pypi.python.org/pypi/pyOpenSSL

![image](https://cloud.githubusercontent.com/assets/597545/23587044/0ff59cca-0208-11e7-8908-d4cffa35203a.png)

I think its time you upgraded to debian jessie.... tbh, you need to upgrade your python to at least 2.7.9... your going to get continued problems like that..

**Comment by Velociraptor85** [comment]
well I guess you are right :/ but I dont want to :) anyways thanks I will check it out maybe next week or another weekend :)

**Comment by VeNoMouS** [comment]
well to be fair, wheezy is over 2 years old and is really outdated now, the SSL you have doesn't even support SNI - https://en.wikipedia.org/wiki/Server_Name_Indication as far as im aware..

Addtionally... 

Python 2.7.9 ... https://www.python.org/downloads/release/python-279/

```
The entirety of Python 3.4's ssl module has been backported for Python 2.7.9. See PEP 466 for justification.
HTTPS certificate validation using the system's certificate store is now enabled by default. See PEP 476 for details.
SSLv3 has been disabled by default in httplib and its reverse dependencies due to the POODLE attack.
The ensurepip module module has been backported, which provides the pip package manager in every Python 2.7 installation. See PEP 477.
```

**Comment by Velociraptor85** [comment]
jap I know .. thanks ... =) 

I just did not want to update because of some issues I could run into with the systemd and stuff but I need to do it somethime :) thanks in advance I will close and reopen if the problem is there afterwards

**Comment by VeNoMouS** [comment]
Yea migrating from systemv to systemd is a nightmare imho, i still dislike systemd.... but what can you do ... ya know?!
