### ISSUE TITLE
Not Downloading a show - IPT

### ISSUE THREAD

**Issue by nidserz** [VeNoMouS/Sick-Beard#12]
Hi, 

For some reason my sickbeard isn't download the latest (March 15) episode of Black-ish.
See the log:

```
2017-03-23 02:38:09 INFO     SEARCHQUEUE-BACKLOG-281511 :: Finished searching for episodes from Black-ish season 3
2017-03-23 02:38:09 INFO     SEARCHQUEUE-BACKLOG-281511 :: [IPTorrents] parseResults()) Some results found.
2017-03-23 02:38:09 INFO     SEARCHQUEUE-BACKLOG-281511 :: [IPTorrents] parseResults()) Some results found.
2017-03-23 02:38:07 INFO     SEARCHQUEUE-BACKLOG-281511 :: Searching for stuff we need from Black-ish season 3
```

Any ideas why this may be happening? Was working okay before.

**Comment by VeNoMouS** [comment]
@nidserz let me throw in some debugging and lets see whats going on, give me a little bit, as pretty busy at work, i'll see what I can do during lunch..

**Comment by nidserz** [comment]
@VeNoMouS no problem, take your time. thanks a lot!

**Comment by VeNoMouS** [comment]
Hey @nidserz sorry I haven't forgotten about you, I've just been really busy with work, i travelled half way around the world for a week then back again for work.. Your #1 in my queue for outside of work stuff.

**Comment by VeNoMouS** [comment]
@nidserz under your 'debug' drop down in view log , what does it say above , 
``` [IPTorrents] parseResults()) Some results found.```

it should be like

```Title: <name_here>```

**Comment by VeNoMouS** [comment]
If I manually do what the ipt provider in SB is doing...

I get the following results.... which is correct, so I'm just trying to track down the issue ... can you email a clean backlog manual search for a black-ish episode please?

![image](https://cloud.githubusercontent.com/assets/597545/24686394/cb62a7d4-1a07-11e7-8855-db2844cdaf13.png)

**Comment by VeNoMouS** [comment]
Question.... your not searching for "SD" quality are you? as there is only 2 episodes in SD quality from season 3 , both being episode 9....

![image](https://cloud.githubusercontent.com/assets/597545/24686511/91f52908-1a08-11e7-9027-f40e9a3edd31.png)

**Comment by nidserz** [comment]
@Hi VeN, sorry for the late reply - was traveling for two weeks. I am searching for "SD" quality... strange as all the other episodes, as well as the latest (e20) were snatched and downloaded fine. Just episode 19 is having an issue. Maybe I should download it manually? Or let me know what further information you need.

**Comment by VeNoMouS** [comment]
aaaah i see why, ```Black-ish``` has a scene exceptions.

![image](https://cloud.githubusercontent.com/assets/597545/24778876/0a4ca48e-1b81-11e7-97d8-78f4b59fc719.png)

I'll test the output again with the scene exception name and get back to you.

**Comment by VeNoMouS** [comment]
@nidserz is this still an issue?

**Comment by nidserz** [comment]
Still only for that episode. The others downloaded ok so should be fine.

**Comment by VeNoMouS** [comment]
@nidserz so i assume you mean S03E18? 

![image](https://user-images.githubusercontent.com/597545/28145574-628c09ae-67c7-11e7-9fb7-abc45bae74e9.png)

You would assume the 480p would match... how ever

```
        if checkName(["(pdtv|hdtv|dsr|tvrip).(xvid|x264|h264|x265|h265)"], all) and not checkName(["(720|1080)[pi]"], all) and not checkName(["hr.ws.pdtv.x264"], any):
            return Quality.SDTV
        elif checkName(["webdl|web.dl|\.web\.| web |webrip|web.rip", "xvid|h.?264|x264|h264|x265|h265"], all) and not checkName(["(720|1080)[pi]"], all):
            return Quality.SDTV
```

since it does not contain hdtv or web* in the title as an enforcement on quality for SDTV tagging... it's ignored due to not matching all tags..
