### ISSUE TITLE
Not Processing Riverdale

### ISSUE THREAD

**Issue by nidserz** [VeNoMouS/Sick-Beard#13]
Hi VeN,

I downloaded a new show - Riverdale - using IPT, manually.
However, want to process the downloaded shows into the folders. It isn't able to process.

SickBeard created a folder called "Riverdale", but the episodes are not moving to the folder.

How I have it set up is... completed torrents go into a folder
Torrents > Completed
That folder is then processed and then shows are sent to their respective folders
It should go into:
TV Shows > Riverdale > Season 1

The completed downloads for Riverdale have not moved.

The log is very long - how can I share this with you?

I think the issue is it's called Riverdale, but the torrents I downloaded are Riverdale US - so it is not picking up the information? Any ideas?

**Comment by VeNoMouS** [comment]
Can I get some context, SD ? screen shot of some filenames etc.. find the section in your log where it tries to move it etc...

**Comment by VeNoMouS** [comment]
@nidserz .....

**Comment by nidserz** [comment]
Ok, so SickBeard downloaded the latest episode and it processed it fine - the ones not sorting (manually downloaded) have "US" in the title. The latest episode (automatically) downloaded did not. I guess I have to remove the US in the title. Does this screenshot help?

![screen shot 2017-04-21 at 12 04 20 pm](https://cloud.githubusercontent.com/assets/12033271/25268690/bd885548-268a-11e7-8b1f-9694ff755d05.png)

**Comment by VeNoMouS** [comment]
That will most likely be due to no scene exception I'll add one in and you can re-test it

![image](https://cloud.githubusercontent.com/assets/597545/25300023/ced11a6c-275a-11e7-8df1-4cea963b5ece.png)

**Comment by VeNoMouS** [comment]
Ok, an update has been placed in scene exceptions, if you want to take effect straight away...

![image](https://cloud.githubusercontent.com/assets/597545/25300066/74cf9498-275b-11e7-8b89-bfbc045afee9.png)

**Comment by VeNoMouS** [comment]
@nidserz let me know how you go, so i can close this off please.

**Comment by nidserz** [comment]
@VeNoMouS you're a genius. no idea what you did, but it works :) you can close. thanks as always!
