### ISSUE TITLE
Torrentleech not finding any results

### ISSUE THREAD

**Issue by nick-harper** [VeNoMouS/Sick-Beard#14]
Hi,

For some reason Torrentleech doesn't seem to find anything, it is using the classic URL but even if it is something like a Family Guy that I know is there with loads of uploaders it just doesn't seem to find anything.

Is there anything I can do as a test?

**Comment by nick-harper** [comment]
Is it possible to make it debug to the log the URL it is trying so I can try it manually in the browser?

**Comment by nick-harper** [comment]
Ah, looking in the file I have now got it to show the URL it is trying.

An example link is: https://classic.torrentleech.org/torrents/browse/index/query/Bosch S01E01/categories/26,27,32

That gives 2 results, Sickbeard says no results :(

**Comment by VeNoMouS** [comment]
What do you have your quality `type` set to, HD720p? I'll investigate it today

**Comment by nick-harper** [comment]
Thanks, I just have it set to HD.

I just set it to any, and the same still happens.

**Comment by VeNoMouS** [comment]
rgr rgr, thanks sorry, i been off work today with an injury and slept most of today ... will look into it shortly for you mate :)

**Comment by nick-harper** [comment]
Oh :( Hope you feel better soon 👍

**Comment by VeNoMouS** [comment]
Hrmm... was this *wanted* or was it a manual query?

![image](https://user-images.githubusercontent.com/597545/28236708-eb402b4e-6980-11e7-8801-05f1bafbaa14.png)

```
17:11:27 INFO::SEARCHQUEUE-MANUAL-SEARCH :: Beginning manual search for Bosch - 1x01 - Tis the Season
17:11:27 INFO::SEARCHQUEUE-MANUAL-SEARCH :: Searching for Bosch - 1x01 - Tis the Season
17:11:27 INFO::SEARCHQUEUE-MANUAL-SEARCH :: Searching TorrentLeech for Bosch - 1x01 - Tis the Season
17:11:27 INFO::SEARCHQUEUE-MANUAL-SEARCH :: [TorrentLeech] Performing Search: Bosch S01E01
17:11:28 INFO::SEARCHQUEUE-MANUAL-SEARCH :: [TorrentLeech] parseResults() Some results found.
17:11:28 INFO::SEARCHQUEUE-MANUAL-SEARCH :: Quality of Bosch S01E01 INTERNAL 720p WEBRiP x264-FaiLED is 720p WEB-DL
17:11:28 INFO::SEARCHQUEUE-MANUAL-SEARCH :: Quality of Bosch S01E01 Pilot 720p WEBRip x264-W4F is 720p WEB-DL
17:11:28 INFO::SEARCHQUEUE-MANUAL-SEARCH :: Picked Bosch S01E01 Pilot 720p WEBRip x264-W4F as the best
17:11:28 INFO::SEARCHQUEUE-MANUAL-SEARCH :: Downloading episode from https://www.torrentleech.org/download/492552/Bosch.S01E01.Pilot.720p.WEBRip.x264-W4F.torrent
17:11:28 INFO::SEARCHQUEUE-MANUAL-SEARCH :: Downloading a result from TorrentLeech at https://www.torrentleech.org/download/492552/Bosch.S01E01.Pilot.720p.WEBRip.x264-W4F.torrent
```

**Comment by nick-harper** [comment]
It was manual :(

**Comment by VeNoMouS** [comment]
Are you running my branch? can you send me the debug log please, that is a fresh git, simply added TL as a provider, and did a manual search for S01E01.

**Comment by nick-harper** [comment]
I thought it was, but come to think of it I recently upgraded so not sure if it has taken another version.

Just downloaded your files again and moved them over but got:

16:53:27 ERROR::MAIN :: Your database version (19) has been incremented past what this version of Sick Beard supports (18).
If you have used other forks of Sick Beard, your database may be unusable due to their modifications.

:(

Sorry.

**Comment by nick-harper** [comment]
Thanks, I just removed the dir, just used your code and it works. I know I was using your code before but when I updated it must have updated with something else :( 

Sorry and thanks for your time!

**Comment by VeNoMouS** [comment]
You can export the data out and insert it back in, its not all that hard tbh its jsut an sqlite db..

**Comment by VeNoMouS** [comment]
And np, least we got there in the end :)
