### ISSUE TITLE
500 Internal Server Error 

### ISSUE THREAD

**Issue by nidserz** [VeNoMouS/Sick-Beard#15]
Suddenly got this 500 Internal Error when trying to access the SB page in my browser. Any idea how to fix this? Tried some solutions on Google but nothing helped. Got it to load funny at times, but clicking or refreshing just leads back to this.

<img width="746" alt="screen shot 2017-09-20 at 7 36 02 pm" src="https://user-images.githubusercontent.com/12033271/30653039-041f86de-9e3b-11e7-9b19-55d5b97785e0.png">

**Comment by DirtyJerz** [comment]
Looks like there's something wrong with the database. Did you move the installation to another location or change the permissions on the .db file?

**Comment by VeNoMouS** [comment]
Yea that looks like theres an issue with your database... email me through your sickbeard.db files ill take a look for you.

@DirtyJerz since its a sqlite database, sometimes they do corrupt... which is possible

**Comment by VeNoMouS** [comment]
Issue was at users end, a restart of sickbeard resolved issue.
