### ISSUE TITLE
Can't use database going from Juanmeida's version

### ISSUE THREAD

**Issue by jappish84** [VeNoMouS/Sick-Beard#16]
I tried to move from Junalmeida's version to this version, but get the error: 

```
Your database version (19) has been incremented past what this version of Sick Beard supports (18).
If you have used other forks of Sick Beard, your database may be unusable due to their modifications.
```
Is there some way I can move to this version without having to manually reconfigure everything?

**Comment by VeNoMouS** [comment]
You are using his subtitles branch yes?

**Comment by VeNoMouS** [comment]
The subtitles branch database has a slightly different schema layout, but you can manually export the required data to the normal database, i can give you the command if that's what you want?

**Comment by jappish84** [comment]
Yes, I'm using the subtitle branch - which is great

I would really appreciate some help moving over - Junalmedia's version isn't working that good anymore - misses alot of episodes, keep getting "_doSearch() invalid json returned." for torrentday

Thanks

**Comment by VeNoMouS** [comment]
Yea, so you need to be aware, he ran into some major problems with some of the modules in the subtitles branch, so he stopped development on it, and i never maintained that branch, i only do the torrentProviders branch, but thats cool I can help you out converting your sickbead.db , you have 2 options, i can give you the commands and you can it yourself , or you can just email me your sickbeard.db (dont worry all your torrent login details are in the sickbeard.ini not the db, the db only holds what episodes you want and what you have downloaded.) 

let me know which option you want to go, it'll only take me a couple minutes to do the conversion for you

**Comment by jappish84** [comment]
I really appreciate the help, thank you! - check your email =)

**Comment by DirtyJerz** [comment]
@VeNoMouS You're the man. (or woman, unclear)

**Comment by VeNoMouS** [comment]
lol, im a dude, got your email , gotta pop out this morning, but will do it for you this afternoon if that's cool.

**Comment by VeNoMouS** [comment]
I've mailed the db back to you, it wasn't actually as bad as what i thought it was going to be, i checked the schema's of each table, and i simply bumped the db_version back down to 18.

**Comment by VeNoMouS** [comment]
The only differences where just orders of the columns ... and spaces in the schema..

```
3c3
< CREATE INDEX idx_tv_episodes_showid_airdate ON tv_episodes (showid,airdate);
---
> CREATE INDEX idx_tv_episodes_showid_airdate ON tv_episodes(showid,airdate);
7c7
< CREATE TABLE tv_episodes (episode_id INTEGER PRIMARY KEY, showid NUMERIC, tvdbid NUMERIC, name TEXT, season NUMERIC, episode NUMERIC, description TEXT, airdate NUMERIC, hasnfo NUMERIC, hastbn NUMERIC, hassrt NUMERIC, status NUMERIC, location TEXT, file_size NUMERIC, release_name TEXT);
---
> CREATE TABLE tv_episodes (episode_id INTEGER PRIMARY KEY, showid NUMERIC, tvdbid NUMERIC, name TEXT, season NUMERIC, episode NUMERIC, description TEXT, airdate NUMERIC, hasnfo NUMERIC, hastbn NUMERIC, status NUMERIC, location TEXT, file_size NUMERIC, release_name TEXT, hassrt NUMERIC);
``

**Comment by jappish84** [comment]
Thanks man, I've tried it and Sickbeard seems to load the database as it's supposed to. I have another issue now though - can't reach web-ui with your version, I've described the details in the email.

Thanks again!

**Comment by VeNoMouS** [comment]
```
-a <ipaddr> --addr=<ipaddr>     Override default/configured ip address to listen on
-p <port>   --port=<port>       Override default/configured port to listen on
```

**Comment by jappish84** [comment]
Thanks, ended up changing it in the config.ini file. Must have been tired or something earlier

**Comment by VeNoMouS** [comment]
Just as an FYI... I am rewriting the frontend as well... since that's liker a billion years old...

**Comment by jappish84** [comment]
Cool - looking forward to trying that out =)

Looks like torrentday did some changes on their part? Still keep getting "_doSearch() invalid json returned." even with your version. Care to take a look? Should I open a seperate issue?

**Comment by VeNoMouS** [comment]
Yea refer https://github.com/junalmeida/Sick-Beard/issues/321 , issue has only been discovered recently, I have to write a workaround.
