### ISSUE TITLE
torrentday not working anymore

### ISSUE THREAD

**Issue by jappish84** [VeNoMouS/Sick-Beard#17]
same problem as reported here: https://github.com/junalmeida/Sick-Beard/issues/321

I thought I'd let TD hear my voice aswell and asked them to cooperate, user thebang referred to try and use https://torrentday.com/sign-in.php?  

When email address is entered in the field, a one-time sign in url is sent back to the email address - maybe this is something you can work with?

**Comment by VeNoMouS** [comment]
@jappish84 interesting, I wasn't aware of this one... I wonder how long that token is valid for...

**Comment by VeNoMouS** [comment]
seems it's a one time usage... my concern is about if you restart SB or if their site is offline long enough your session becomes invalid.. means you have to re-do the code each time.

**Comment by VeNoMouS** [comment]
If you look at the original ticket, I have worked out how to bypass their recaptcha.. but it costs 0.002 cents a shot.

**Comment by VeNoMouS** [comment]
Re from original ticket...

so we currently have three points of attack

1) Bypass reCAPTCHA all together via 3rd party, complete automation and never worry about auth again.
2) Login to website, manually extract cookies from browser and put them into SB running session.
3) Automate an email password request, have user manually copy auth code from the email response back into SB current running session and then authenticate. 

As i've pointed out tho, 2 & 3 are only valid as long as the TD session is valid for... what that period is... i don't know.

**Comment by VeNoMouS** [comment]
Sorry I have been out of the country all week so haven't had time to actually do anymore on this, I did #18 yesterday and pushed live today.

This will be my next priority job to do.

**Comment by jappish84** [comment]
Yeah, no worries, you are doing a great job.

I'm okay with whatever solution you decide to go with, even of it means using a third party auth

**Comment by VeNoMouS** [comment]
Small update on this as been working on it today...

![image](https://user-images.githubusercontent.com/597545/38161203-d741903e-3526-11e8-8bb9-4d0b4b5cf694.png)

With the anti-captcha it stores it away for later use into the cookie storage :P

Just have the email token request to do.

![image](https://user-images.githubusercontent.com/597545/38161271-92af5242-3528-11e8-966d-a46065a307ab.png)

small look...

![image](https://user-images.githubusercontent.com/597545/38161273-996304e4-3528-11e8-866d-7316b2d58fc6.png)

**Comment by VeNoMouS** [comment]
Have pushed this live, feel free to have a play / test ... what ever, let me know .. it appears to work in all my tests...

**Comment by jappish84** [comment]
Awesome work, will give it a go and let you know!

**Comment by VeNoMouS** [comment]
@jappish84 any comments etc?

**Comment by jappish84** [comment]
Sorry, haven't had the chance, my router got hacked so I had to spend the day updating/reconfiguring a gazillion settings. 

Will test tomorrow and report back

**Comment by jappish84** [comment]
hmm, seems like I'm not getting the newest version. I'm still seeing the old authentication method only. What am I missing here?

`2018-04-04 16:06:14 INFO     CP Server Thread-8 :: Checking if source needs an update
2018-04-04 16:06:11 INFO     CP Server Thread-8 :: No update needed
2018-04-04 16:06:09 INFO     CP Server Thread-8 :: Checking if source needs an update
2018-04-04 16:03:56 INFO     CP Server Thread-8 :: Scene Exceptions Update Completed.
2018-04-04 16:03:55 INFO     CP Server Thread-8 :: No scene exceptions update needed
2018-04-04 16:03:55 INFO     CP Server Thread-8 :: Check scene exceptions update
2018-04-04 16:03:55 INFO     CP Server Thread-8 :: Forcing Scene Exceptions Update
2018-04-04 16:03:50 INFO     CP Server Thread-8 :: No update needed
2018-04-04 16:03:49 INFO     CP Server Thread-8 :: Checking if source needs an update
2018-04-04 16:03:45 INFO     CP Server Thread-8 :: No update needed
2018-04-04 16:03:44 INFO     CP Server Thread-8 :: Checking if source needs an update`

**Comment by VeNoMouS** [comment]
are you using my repo or @junalmeida 's? he hasnt merged the PR i sent him, so only my code has the new features.

**Comment by jappish84** [comment]
Yea, I've made sure I'm using your version, I even double checked it. 

I had an update a few days back that I updated to. Can't find current version in WebUI but here is the contents of version.txt inside Sickbeard folder: efcf0561aa3049df51b45d6ca58606f8bf3ac6d8

**Comment by VeNoMouS** [comment]
@jappish84 you went here

![image](https://user-images.githubusercontent.com/597545/38404883-24ed168e-39c1-11e8-9289-b6ca06cbc4df.png)

then 

![image](https://user-images.githubusercontent.com/597545/38404931-6d404e1a-39c1-11e8-8dd7-875f7ac623d6.png)


Then select your auth method..

![image](https://user-images.githubusercontent.com/597545/38404939-76b2cbf8-39c1-11e8-8acd-05f84ef514dd.png)

**Comment by VeNoMouS** [comment]
You can also confirm your git via `git remote show origin`

which should give you something like

```
* remote origin
  Fetch URL: https://github.com/VeNoMouS/Sick-Beard.git
  Push  URL: https://github.com/VeNoMouS/Sick-Beard.git
  HEAD branch: torrentProviders
  Remote branch:
    torrentProviders tracked
  Local branch configured for 'git pull':
    torrentProviders merges with remote torrentProviders
  Local ref configured for 'git push':
    torrentProviders pushes to torrentProviders (up to date)
```

**Comment by jappish84** [comment]
Yeah, I was there. First I had to create a SSH tunnel because of the old message "Sorry in order to use this function, your URL has to be 127.0.0.1 or localhost" 

After creating the tunnel and visiting 127.0.0.1, the only authentication method was the old reCaptcha

I didn't install through git, I simply downloaded and inflated the .zip, maybe that's why I'm not getting the new version? The update notification usually says I'm nnn commits behind

Should I just backup the .db and .ini and redownload again?

**Comment by VeNoMouS** [comment]
what happens if you force check?

![image](https://user-images.githubusercontent.com/597545/38407459-9d8c9400-39cd-11e8-836a-56eebd66577a.png)

I would simply copy the sickbard.db and config.ini and git clone off my repo and copy your configs over..

**Comment by VeNoMouS** [comment]
Actually... I'm not 100% certain a force check would work with a zip download, as it wont know where the git came from to pull off..

Install via git off my repo mate and let me know how you go.

**Comment by jappish84** [comment]
I simply get 'No update needed'

![upd](https://user-images.githubusercontent.com/3979357/38407718-de1a36e2-397a-11e8-81aa-e952361da72f.png)

I'll try git cloning and let you know

**Comment by VeNoMouS** [comment]
@jappish84 ..... can i close this ticket mate?

**Comment by jappish84** [comment]
I finally got around to test it and it works great mate! Great job as always! A big thank you!

**Comment by VeNoMouS** [comment]
Cool, awesome that it's working for you mate, let me know if you encounter any other problems or want new features added :)

have a good weekend man.
