### ISSUE TITLE
RARBG problem

### ISSUE THREAD

**Issue by dventurino** [VeNoMouS/Sick-Beard#21]
I have lots of these lines in my logs:

`2020-04-17 08:19:27 SEARCHQUEUE-BACKLOG-328724 :: [Rarbg] _doLogin() requested URL: https://torrentapi.org/pubapi_v2.php , requesting token, returned status code 403`

Is this a known issue?

**Comment by VeNoMouS** [comment]
Is it a known issue? no... i havent done anything publicly on SB in ages... but I can look into it for you :)

**Comment by dventurino** [comment]
Damn you are fast :) 

Isn't app_id already specified at line 356 of rarbg.py?

**Comment by VeNoMouS** [comment]
Yea I actually deleted that comment ;P

**Comment by dventurino** [comment]
It looks like passing values in the url works, while setting them as json params doesn't.

> https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=testapp

**Comment by VeNoMouS** [comment]
As json params? 

it doesn't send as json... we only use json from the response payload, as we can use it as a dict

https://github.com/VeNoMouS/Sick-Beard/blob/torrentProviders/sickbeard/providers/rarbg.py#L355-L359

Notice how its `params` not `json`

**Comment by dventurino** [comment]
So the complete url would be the same.

 I'm  not sure why if fails when called from python but not in a browser
