### ISSUE TITLE
merging with torrent_1080_subtitles

### ISSUE THREAD

**Issue by holocronweaver** [VeNoMouS/Sick-Beard#3]
Hi Venomous!

Any chance you will merge your work into the `torrent_1080_subtitles` branch in the near future?

**Comment by VeNoMouS** [comment]
I don't do that branch.. I normally leave that up to @junalmeida .... but I dunno... I might pick it up in the future... but I don't really want to touch the subtitles branch to be perfectly honest... 

Who knows... maybe when I have more spare time..

tl;dr.... Maybe..

**Comment by holocronweaver** [comment]
My understanding is that `torrent_1080_subtitles` contains both support for subtitle and a 1080 HD filters. Does it do anything else? I assume the other branch at least has a generic HD filter, which would be fine for me 90% of the time. It will be annoying to have to regenerate by DB and config again, but I want to be on the branch which is most likely to continue being updated.

**Comment by VeNoMouS** [comment]
no... 720p/1080 is in the tv add/edit section on both branches...

![Image](http://i.imgur.com/oM8QvfS.png)

**Comment by VeNoMouS** [comment]
As for "generating the db again" you shouldn't need too... you should just be able to copy the sickbeard.db and config.ini's over to the other branch and should work...

**Comment by holocronweaver** [comment]
The database version in the 1080_subtitle repo is 15, but the one in your repo is 18 and one has fields the other doesn't have. Also, config file version in your repo is higher. Still, the original config and DB were backed up, so I can always regress if I really need to.

**Comment by VeNoMouS** [comment]
I'm going to close this for now.
