### ISSUE TITLE
Request Upgrade path

### ISSUE THREAD

**Issue by Velociraptor85** [VeNoMouS/Sick-Beard#9]
Is there an upgrade path from junalmedia's branch to yours ? I mean that my configs are not lost ?

**Comment by VeNoMouS** [comment]
which branch are you using? if your using torrentProviders branch , you can simply copy the config.ini and sickbeard.db in your existing install to clone of mine, and you'll be up and running again. if your using subtitles branch... that's a little different you'll have to do a dump in sickbeard.db its sqlite3 as some of the columns are different etc..

**Comment by Velociraptor85** [comment]
seems to have worked :) thanks 👍

**Comment by VeNoMouS** [comment]
np :)
